//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteFly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoteFly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hoekje {
            get {
                object obj = ResourceManager.GetObject("hoekje", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap locknote {
            get {
                object obj = ResourceManager.GetObject("locknote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.\r\nPlease choice a valid directory..
        /// </summary>
        public static string settings_dirdoesnotexist {
            get {
                return ResourceManager.GetString("settings_dirdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        public static string settings_dirdoesnotexisttitle {
            get {
                return ResourceManager.GetString("settings_dirdoesnotexisttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given default emailadres is not valid..
        /// </summary>
        public static string settings_emailnotvalid {
            get {
                return ResourceManager.GetString("settings_emailnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is marked as system file. Did not move..
        /// </summary>
        public static string settings_excsystemfilenotmoved {
            get {
                return ResourceManager.GetString("settings_excsystemfilenotmoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note file(s) already exist..
        /// </summary>
        public static string settings_filealreadyexist {
            get {
                return ResourceManager.GetString("settings_filealreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current font for note content cannot be found..
        /// </summary>
        public static string settings_fontnotecontentnotfound {
            get {
                return ResourceManager.GetString("settings_fontnotecontentnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to gpg.exe is not valid..
        /// </summary>
        public static string settings_gpgpathinvalid {
            get {
                return ResourceManager.GetString("settings_gpgpathinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated.
        /// </summary>
        public static string settings_infoupdated {
            get {
                return ResourceManager.GetString("settings_infoupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder for saving notes folder..
        /// </summary>
        public static string settings_invalidfoldersavenote {
            get {
                return ResourceManager.GetString("settings_invalidfoldersavenote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size invalid. Minimal 4pt maximum 128pt allowed..
        /// </summary>
        public static string settings_invalidfontsize {
            get {
                return ResourceManager.GetString("settings_invalidfontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a font..
        /// </summary>
        public static string settings_nofont {
            get {
                return ResourceManager.GetString("settings_nofont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings text direction invalid..
        /// </summary>
        public static string settings_noknowtextdir {
            get {
                return ResourceManager.GetString("settings_noknowtextdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkstate not allowed..
        /// </summary>
        public static string settings_notallowcheckstate {
            get {
                return ResourceManager.GetString("settings_notallowcheckstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run key in registery does not exist..
        /// </summary>
        public static string settings_regkeynotexist {
            get {
                return ResourceManager.GetString("settings_regkeynotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to reset all the settings to default?.
        /// </summary>
        public static string settings_sureresetdefault {
            get {
                return ResourceManager.GetString("settings_sureresetdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings?.
        /// </summary>
        public static string settings_sureresetdefaulttitle {
            get {
                return ResourceManager.GetString("settings_sureresetdefaulttitle", resourceCulture);
            }
        }
    }
}
